var msg = ("Error! Please enter a valid password.")
alert(msg)
var wlcmmsg = ("Welcome to JS Land...  \n Happy Coding!")
alert(wlcmmsg)
var welcome = ("Welcome to JS Land...")
alert(welcome)
    var Happycode = ("Happy Coding! \n prevent this page from creating additional dialogs.")
alert(welcome)
var hello = ("Hello...I can run JS through my web browser's console")
alert(hello)